# -*- coding: utf-8 -*-
"""RS Task 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nf6Q9IHH5kBeKGe1BFRai4UuBIfnaIV6
"""

import sqlite3
import pandas as pd

# Load your CSV
df = pd.read_csv("/content/Sales_Data.csv")

# Create and connect to SQLite database
conn = sqlite3.connect("Sales_Data.db")

# Save DataFrame as a table in SQLite
df.to_sql("sales", conn, if_exists="replace", index=False)

import pandas as pd
import sqlite3

query = """
SELECT
    `product id`,
    SUM(orders) AS total_items_sold,
    SUM(`price inr`) AS total_revenue
FROM df
GROUP BY `product id`
ORDER BY total_revenue DESC
"""

# If your data is in a DataFrame 'df':
result_df = df.groupby('product_id').agg(
    total_items_sold=('orders', 'sum'),
    total_revenue=('price_inr', 'sum')
).sort_values(by='total_revenue', ascending=False).reset_index()

print(result_df.head())

product_revenue = df.groupby('product_id')['price_inr'].sum().sort_values(ascending=False)

# Get the top 10 products by revenue
top_10_revenue = product_revenue.head(10)

# Create the bar plot
plt.figure(figsize=(10, 6))
top_10_revenue.plot(kind="bar")
plt.title("Top 10 Products by Revenue")
plt.xlabel("Product ID")
plt.ylabel("Total Revenue (INR)")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.savefig("top_products_revenue.png")
plt.show()